function [persons, birds, cats, cows, dogs, horses, sheeps, aeroplanes, bicycles, boats, buses, cars, motorbikes, trains, bottles, chairs, diningtables, pottedplants, sofas, tvmonitors] = rearr(overlaps)   
    % create array per class
    persons = overlaps(:,:,1);
    birds = overlaps(:,:,2);
    cats = overlaps(:,:,3);
    cows = overlaps(:,:,4);
    dogs = overlaps(:,:,5);
    horses = overlaps(:,:,6);
    sheeps = overlaps(:,:,7);
    aeroplanes = overlaps(:,:,8);
    bicycles = overlaps(:,:,9);
    boats = overlaps(:,:,10);
    buses = overlaps(:,:,11);
    cars = overlaps(:,:,12);
    motorbikes = overlaps(:,:,13);
    trains = overlaps(:,:,14);
    bottles = overlaps(:,:,15);
    chairs = overlaps(:,:,16);
    diningtables = overlaps(:,:,17);
    pottedplants = overlaps(:,:,18);
    sofas = overlaps(:,:,19);
    tvmonitors = overlaps(:,:,20);
    % delete rows/columns, without entry (-1 was the initialization)
    persons(all(persons==-1,2),:) = [];
    persons( :, all(persons==-1,1) ) = [];
    birds(all(birds==-1,2),:) = [];
    birds( :, all(birds==-1,1) ) = [];
    cats(all(cats==-1,2),:) = [];
    cats( :, all(cats==-1,1) ) = [];
    cows(all(cows==-1,2),:) = [];
    cows( :, all(cows==-1,1) ) = [];
    dogs(all(dogs==-1,2),:) = [];
    dogs( :, all(dogs==-1,1) ) = [];
    horses(all(horses==-1,2),:) = [];
    horses( :, all(horses==-1,1) ) = [];
    sheeps(all(sheeps==-1,2),:) = [];
    sheeps( :, all(sheeps==-1,1) ) = [];
    aeroplanes(all(aeroplanes==-1,2),:) = [];
    aeroplanes( :, all(aeroplanes==-1,1) ) = [];
    bicycles(all(bicycles==-1,2),:) = [];
    bicycles( :, all(bicycles==-1,1) ) = [];
    boats(all(boats==-1,2),:) = [];
    boats( :, all(boats==-1,1) ) = [];
    buses(all(buses==-1,2),:) = [];
    buses( :, all(buses==-1,1) ) = [];
    cars(all(cars==-1,2),:) = [];
    cars( :, all(cars==-1,1) ) = [];
    motorbikes(all(motorbikes==-1,2),:) = [];
    motorbikes( :, all(motorbikes==-1,1) ) = [];
    trains(all(trains==-1,2),:) = [];
    trains( :, all(trains==-1,1) ) = [];
    bottles(all(bottles==-1,2),:) = [];
    bottles( :, all(bottles==-1,1) ) = [];
    chairs(all(chairs==-1,2),:) = [];
    chairs( :, all(chairs==-1,1) ) = [];
    diningtables(all(diningtables==-1,2),:) = [];
    diningtables( :, all(diningtables==-1,1) ) = [];
    pottedplants(all(pottedplants==-1,2),:) = [];
    pottedplants( :, all(pottedplants==-1,1) ) = [];
    sofas(all(sofas==-1,2),:) = [];
    sofas( :, all(sofas==-1,1) ) = [];
    tvmonitors(all(tvmonitors==-1,2),:) = [];
    tvmonitors( :, all(tvmonitors==-1,1) ) = [];
    
    [uniques,numUnique] = count_unique(persons);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('persons.csv', list);
    [uniques,numUnique] = count_unique(birds);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('birds.csv', list);
    [uniques,numUnique] = count_unique(cats);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('cats.csv', list);
    [uniques,numUnique] = count_unique(cows);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('cows.csv', list);
    [uniques,numUnique] = count_unique(dogs);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('dogs.csv', list);
    [uniques,numUnique] = count_unique(horses);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('horses.csv', list);
    [uniques,numUnique] = count_unique(sheeps);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('sheep.csv', list);
    [uniques,numUnique] = count_unique(aeroplanes);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('aeros.csv', list);
    [uniques,numUnique] = count_unique(bicycles);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('bicycles.csv', list);
    [uniques,numUnique] = count_unique(boats);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('boats.csv', list);
    [uniques,numUnique] = count_unique(buses);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('buses.csv', list);
    [uniques,numUnique] = count_unique(cars);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('cars.csv', list);
    [uniques,numUnique] = count_unique(motorbikes);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('motorbikes.csv', list);
    [uniques,numUnique] = count_unique(trains);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('trains.csv', list);
    [uniques,numUnique] = count_unique(bottles);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('bottles.csv', list);
    [uniques,numUnique] = count_unique(chairs);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('charis.csv', list);
    [uniques,numUnique] = count_unique(diningtables);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('diningtables.csv', list);
    [uniques,numUnique] = count_unique(pottedplants);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('plants.csv', list);
    [uniques,numUnique] = count_unique(sofas);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('sofas.csv', list);
    [uniques,numUnique] = count_unique(tvmonitors);
    list = [uniques(2:end) numUnique(2:end)];
    list = erase_duplicates(list);
    csvwrite('tvs.csv', list);
end